import { useEffect, useState } from "react";
import axios from "axios";
import { BarChart3, BriefcaseBusiness, CircleUserRound, Sparkles } from "lucide-react";
import { useNavigate } from "react-router-dom";
import API from "../config/api";

const fields = ["firstName", "lastName", "phone", "city", "education", "skills", "languages", "sectorOfInterest", "preferences", "cv"];
function completeness(profile) { return Math.round(fields.filter(key => Array.isArray(profile?.[key]) ? profile[key].length : profile?.[key]).length / fields.length * 100); }

export default function Dashboard() {
  const navigate = useNavigate(); const [profile, setProfile] = useState(null); const [history, setHistory] = useState([]); const [loading, setLoading] = useState(true);
  useEffect(() => { (async () => { try { const headers = { Authorization: `Bearer ${localStorage.getItem("token")}` }; const [profileResponse, historyResponse] = await Promise.all([axios.get(`${API}/users/profile`, {headers}), axios.get(`${API}/internships/recommend/history`, {headers})]); setProfile(profileResponse.data); setHistory(historyResponse.data); } catch { navigate("/signin"); } finally { setLoading(false); } })(); }, [navigate]);
  if (loading) return <div className="p-12 text-center text-slate-600">Loading your CareerMatch dashboard…</div>;
  const score = completeness(profile); const gaps = [...new Set(history.flatMap(entry => entry.missingSkills || []))].slice(0, 5);
  const stats = [["Profile strength", `${score}%`, CircleUserRound], ["Recommendations generated", String(history.length), Sparkles], ["Recent average match", history.length ? `${Math.round(history.reduce((sum, item) => sum + (item.matchScore || 0), 0) / history.length)}%` : "—", BarChart3]];
  return <main className="min-h-screen bg-slate-50 px-4 py-10"><div className="mx-auto max-w-6xl"><header className="mb-8"><p className="text-sm font-bold uppercase tracking-wider text-blue-600">CareerMatch dashboard</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Welcome back{profile?.firstName ? `, ${profile.firstName}` : ""}</h1><p className="mt-2 text-slate-600">Track profile readiness and understand where to focus your upskilling.</p></header><section className="grid gap-4 md:grid-cols-3">{stats.map(([label, value, Icon]) => <div key={label} className="rounded-2xl bg-white p-5 shadow-sm"><Icon className="mb-4 text-blue-600"/><p className="text-sm text-slate-600">{label}</p><p className="mt-1 text-3xl font-bold text-slate-900">{value}</p></div>)}</section><section className="mt-6 grid gap-6 lg:grid-cols-5"><div className="rounded-2xl bg-white p-6 shadow-sm lg:col-span-3"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Top recommended internships</h2><p className="text-sm text-slate-600">Your most recent recommendation activity</p></div><button onClick={() => navigate("/recommendations")} className="font-semibold text-blue-700">View all</button></div><div className="mt-5 space-y-3">{history.slice(0, 5).map(item => <div key={`${item.internshipId}-${item.generatedAt}`} className="flex items-center justify-between rounded-xl bg-slate-50 p-4"><div><p className="font-semibold text-slate-900">{item.internshipTitle}</p><p className="text-sm text-slate-600">{item.companyName}</p></div><span className="rounded-full bg-blue-100 px-3 py-1 text-sm font-bold text-blue-800">{item.matchScore ?? 0}%</span></div>)}{!history.length && <div className="rounded-xl border border-dashed p-6 text-center text-slate-600">Generate recommendations to see your history here.</div>}</div></div><aside className="rounded-2xl bg-white p-6 shadow-sm lg:col-span-2"><h2 className="text-lg font-bold">Skill gap focus</h2><p className="mt-1 text-sm text-slate-600">Most frequent gaps from viewed recommendations.</p><div className="mt-5 flex flex-wrap gap-2">{gaps.length ? gaps.map(skill => <span key={skill} className="rounded-full bg-rose-50 px-3 py-1.5 text-sm font-medium text-rose-800">{skill}</span>) : <p className="text-sm text-slate-500">Generate a recommendation to identify skill gaps.</p>}</div><button onClick={() => navigate("/internship-form")} className="mt-8 inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white"><BriefcaseBusiness size={17}/>Update profile</button></aside></section></div></main>;
}
